# Generated by Django 2.2.6 on 2020-09-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20200929_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Plan',
        ),
    ]
