# Generated by Django 2.2.6 on 2020-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200929_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipeplan',
            unique_together={('meal_name', 'day_name'), ('order', 'day_name')},
        ),
        migrations.DeleteModel(
            name='DayName',
        ),
    ]
