# Generated by Django 2.2.6 on 2020-09-29 21:23

from django.db import migrations

DAY_NAMES = (
    (1, 'Poniedziałek'),
    (2, 'Wtorek'),
    (3, 'Środa'),
    (4, 'Czwartek'),
    (5, 'Piątek'),
    (6, 'Sobota'),
    (7, 'Niedziela')
)


def add_day_names(apps, schema_editor):
    DayName = apps.get_model('jedzonko', 'DayName')
    for day in DAY_NAMES:
        DayName.objects.create(order=day[0], day_name=day[1])


class Migration(migrations.Migration):
    dependencies = [
        ('jedzonko', '0006_dayname'),
    ]

    operations = [
        migrations.RunPython(add_day_names)
    ]
