# Generated by Django 2.2.6 on 2020-09-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_auto_20200929_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.DayName'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeplan',
            unique_together={('order', 'day_name', 'plan'), ('meal_name', 'day_name', 'plan')},
        ),
    ]
