# Generated by Django 2.2.6 on 2020-10-02 15:49

from django.db import migrations

PAGES = (
    ('O aplikacji',
     """Jedzenie jest jedną z podstawowych potrzeb człowieka. Ale co zrobić w sytuacji gdy nie masz czasu
     na zaplanowanie jedzenia? Przestać jeść? A może spędzać całe dnie na planowaniu? Nic bardziej mylnego!
    Z pomocą przychodzi aplikacja <b>Zaplanuj jedzonko</b>!
    Będziesz odżywiał się zdrowo i wesoło! A wszystko pod okiem wspaniałej kucharki - Pani Marii Iksińskiej!""",
     'about'),
    ('Kontakt',
     """<p>Maria Iksińska</p>
    <p>e-mail: marysia@mix.pl</p>
    <p>nr tel.: 538 649 109</p>""",
     'contact')
)


def add_pages(apps, schema_editor):
    Page = apps.get_model('jedzonko', 'Page')
    for page in PAGES:
        Page.objects.create(title=page[0], description=page[1], slug=page[2])

class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_page'),
    ]

    operations = [
        migrations.RunPython(add_pages)
    ]
