RECIPE_DATA = (
    ('Smażony ryż z kalafiora po meksykańsku',
     'cebula, czosnek, oliwa z oliwek, kalafior, papryczka chilli wędzona papryka, kmin rzymski, bulion, pomidory, syrop z agawy, czerwona papryka, sól, pieprz',
     'Meksykańskie smaki, które pokochają nie tylko weganie, czyli smażony ryż z kalafiora z mnóstwem warzyw, przypraw i ziół – sycący roślinny obiad z charakterem!',
     40),
    ('Sałatka z owocami i francuskim serem',
     'ser pavé, borówki amerykańskie, maliny, truskawki, gruszka bio, miód, mix sałat, liście kopru włoskiego, szczypiorek, świeża bazylia',
     'Aromatyczna, świeża, pełna ziół i różnorodnych smaków – sałatka z serem pavé, owocami i sosem na bazie octu balsamicznego sprawi, że zakochasz się w kuchni francuskiej!',
     35),
    ('Zapiekanka ziemniaczana',
     'ziemniaki bio, pieczarki, śmietanka, suszone pomidory w oleju, olej po suszonych pomidorach, cebula, czosnek, natka pietruszki, majeranek, świeży rozmaryn, olej słonecznikowy, masło, grana padano, sól, pieprz',
     'Na spotkanie ze znajomymi, na rodzinny obiad – zapiekanka ziemniaczana to szybkie, proste i sycące danie na wiele okazji! Upiecz ją i sprawdź, jak smakuje!',
     90),
    ('Wegańskie ciasteczka imbirowe',
     'mąka pszenna, mielony imbir, proszek do pieczenia, sól, syrop klonowy, olej kokosowy, woda, czekolada gorzka, precelki, draże czekoladowe, gwiazdki cukrowe',
     'Są wegańskie, imbirowe i przypominają renifery! Te ciasteczka na pewno zasmakują wszystkim, nie tylko najmłodszym fanom mikołajkowych słodkości! ',
     35),
    ('Naleśniki z twarożkiem',
     'mąka przenna, twarożek, mleko, jajka, masło, bita śmietana, owoce, cukier',
     'Te przepyszne naleśniki są idealne na niedzielne śniadanie!',
     30),
    ('Soba stir fry z wołowiną',
     'makaron soba, stek z polędwicy wołowej, mielony biały pieprz, cukinia, czerwona cebula, sól, pieprz, ocet balsamiczny, sos sojowy, olej sezamowy, miód, świeży imbir, czosnek, papryczka chili, świeża kolendra, kiełki fasoli mung, skórka limonki',
     'Sprawdź, jak smakuje japoński makaron soba w połączeniu z wołowiną i chrupiącymi warzywami! Przygotuj szybkie soba stir fry według przepisu Karola i ciesz się prawdziwymi smakami Azji! ',
     25),
    ('Butter chicken',
     'garam masala, kurkuma, chili mielone, jogurt grecki, sok wyciśnięty z cytryny, masło klarowane, cebula, czosnek, imbir, kurczak, pomidory z puszki, ryż',
     'Niech smaki i aromaty kuchni indyjskiej zagoszczą na stałe w Twoim menu! Przygotuj butter chicken, czyli kurczaka w kremowym i delikatnie maślanym sosie na bazie pomidorów! ',
     60),
    ('Kurczak teriyaki z warzywami',
     'garam masala, kurkuma, chili mielone, czosnek, jogurt grecki, sok wyciśnięty z cytryny, świeży imbir, masło klarowane, cebula , czosnek, imbir',
     'Lubisz kuchnię japońską? Skorzystaj z przepisu Karola i przygotuj kurczaka w domowym, aromatycznym sosie teriyaki! ',
     45),
    ('Warstwowa panna cotta',
     'śmietanka UHT, mleko, agrest, borówki, żelatyna, zimna woda, cukier puder, świeże maliny, świeża mięta',
     'Panna cotta to znany włoski deser, który Paweł przygotował w nowej, zaskakującej odsłonie. Wypróbuj przepis na warstwową panna cottę i ciesz się jej śmietankowo-owocowym smakiem! ',
     120),
    ('Kajmakowy deser tiramisu',
     'serek mascarpone, ubita śmietanka UHT, masa kajmakowa, mocne espresso, owoce lasu w syropie, syrop z owoców lasu, ciasteczka amaretti, kakao, świeże maliny, świeża mięta',
     'Aksamitny krem kajmakowy, owoce lasu, ciasteczka i wyczuwalny smak mocnej kawy – oto składniki prostego, kuszącego deseru, który przygotujesz dzięki przepisowi Pawła!',
     30),
)
